app.entorno = ${ENTORNO:local}

# No funciona en despliegues de Docker y S2I
quarkus.openshift.route.expose=true
quarkus.kubernetes.deploy=true
quarkus.kubernetes-client.master-url=https://api.crc.testing:6443
quarkus.kubernetes-client.token=sha256~bmYPo-2R-iGcX4SfujY2MZPXJjZ4-3av5MoqGFlrcxM